//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models.DataHandler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class surveyEF : DbContext
    {
        public surveyEF()
            : base("name=surveyEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answer> Answers { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<Survey> Surveys { get; set; }
        public DbSet<Taker> Takers { get; set; }
    
        public virtual ObjectResult<sps_QAforSurvey_Result> sps_QAforSurvey(Nullable<int> surveyid)
        {
            var surveyidParameter = surveyid.HasValue ?
                new ObjectParameter("surveyid", surveyid) :
                new ObjectParameter("surveyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_QAforSurvey_Result>("sps_QAforSurvey", surveyidParameter);
        }
    
        public virtual int spI_Taker(Nullable<int> questionID, Nullable<int> answerID)
        {
            var questionIDParameter = questionID.HasValue ?
                new ObjectParameter("QuestionID", questionID) :
                new ObjectParameter("QuestionID", typeof(int));
    
            var answerIDParameter = answerID.HasValue ?
                new ObjectParameter("AnswerID", answerID) :
                new ObjectParameter("AnswerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spI_Taker", questionIDParameter, answerIDParameter);
        }
    
        public virtual ObjectResult<sps_graphData_Result> sps_graphData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_graphData_Result>("sps_graphData");
        }
    }
}
