//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models.DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taker
    {
        public int TakerId { get; set; }
        public int QuestionID { get; set; }
        public int AnswerID { get; set; }
    }
}
